In [41]:
import pandas as pd

In [86]:
df = pd.read_csv('car_sales_cleaned1.csv')
# show rows for Hyundai Company
dfHyundai = df[df["Company"] == "Hyundai"].reset_index()
dfHyundai

       Gender  Annual Income  Company    Model Transmission       Color  Price ($)
16     Female         535000  Hyundai   Accent       Manual       Black      18000
124    Female        1690000  Hyundai   Sonata       Manual       Black      15000
168      Male         955000  Hyundai  Elantra       Manual  Pale White      26000
250      Male         457000  Hyundai   Sonata       Manual  Pale White      21000
289      Male          13500  Hyundai   Sonata       Manual       Black      20000
...       ...            ...      ...      ...          ...         ...        ...
23432  Female          13500  Hyundai  Elantra       Manual         Red      22000
23580  Female          13500  Hyundai   Sonata       Manual       Black      15000
23650  Female         460000  Hyundai   Sonata       Manual       Black      15000
23738    Male         705000  Hyundai   Sonata       Manual         Red      21000
23745    Male         681500  Hyundai   Accent       Manual       Black      18500

[264 rows x 7 columns]

In [2]:
dfToyotaExp = df.query('Company == "Toyota" and `Price ($)` > 40000').reset_index()
dfToyotaExp

,index,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,239,Male,1350000,Toyota,Tacoma,Auto,Pale White,53000
1,258,Male,1151000,Toyota,Corolla,Auto,Pale White,41100
2,269,Female,825000,Toyota,Tacoma,Manual,Pale White,82000
3,308,Female,13500,Toyota,Corolla,Auto,Pale White,41000
4,358,Male,1326000,Toyota,RAV4,Manual,Black,85600
...,...,...,...,...,...,...,...,...
194,23379,Male,1300000,Toyota,Celica,Auto,Pale White,45001
195,23385,Female,615000,Toyota,Tacoma,Auto,Pale White,53000
196,23443,Male,2400000,Toyota,RAV4,Manual,Black,85000
197,23476,Male,520000,Toyota,Celica,Auto,Pale White,45000
198,23735,Male,1635000,Toyota,Tacoma,Auto,Pale White,53501

In [83]:
mostPopularCars = df[["Model", "Company"]].value_counts().head(3).reset_index()
mostPopularCars

        Model     Company  count
0    Diamante  Mitsubishi    418
1       Prizm   Chevrolet    411
2  Silhouette  Oldsmobile    411