In [3]:
import pandas as pd
df = pd.read_csv('car_sales_cleaned1.csv')
df

       Gender  Annual Income    Company       Model Transmission       Color  Price ($)
0        Male          13500       Ford  Expedition         Auto       Black      26000
1        Male        1480000      Dodge     Durango         Auto       Black      19000
2        Male        1035000   Cadillac    Eldorado       Manual         Red      31500
3        Male          13500     Toyota      Celica       Manual  Pale White      14000
4        Male        1465000      Acura          TL         Auto         Red      24500
...       ...            ...        ...         ...          ...         ...        ...
23901    Male          13500   Plymouth     Voyager       Manual         Red      12000
23902  Female         900000  Chevrolet       Prizm         Auto       Black      16000
23903    Male         705000        BMW        328i       Manual         Red      21000
23904    Male          13500  Chevrolet       Metro         Auto       Black      31000
23905    Male        1225000      Lexus       ES300         Auto  Pale White      27500

[23906 rows x 7 columns]

In [4]:
df = df.drop_duplicates() #removing duplicates
df.shape

(20358, 7)

In [5]:
df = df.dropna() #removing rows with missing values
df.shape

(20358, 7)

In [ ]:
valuesCol = df['Model'].unique()

In [19]:
dfProjected = df[['Company', 'Model']]
dfProjected

         Company       Model
0           Ford  Expedition
1          Dodge     Durango
2       Cadillac    Eldorado
3         Toyota      Celica
4          Acura          TL
...          ...         ...
23898      Volvo         C70
23900       Ford     Contour
23902  Chevrolet       Prizm
23903        BMW        328i
23905      Lexus       ES300

[20358 rows x 2 columns]

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import converter
model = DecisionTreeClassifier()
y = dfProjected[['Company']]
mapper = converter.columnsMapper(['Model', 'Company'], dfProjected)
dfConverted = converter.convertX(dfProjected, mapper)
X = dfConverted[['Company']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
score

0.3267636765518512